spin_manifest_version = 2

[application]
name = "aos2024"
version = "0.1.0"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/api/..."
component = "challenge1"

[component.challenge1]
source = "challenge1/target/wasm32-wasi/release/challenge1.wasm"
key_value_stores = ["default"]
allowed_outbound_hosts = []
dependencies_inherit_configuration = true
[component.challenge1.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "challenge1"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.challenge1.dependencies]
"components:advent-of-spin/generator@0.1.0" = { path = "challenge3/gift-suggestions-generator.wasm" }
"advent-of-spin:challenge-two/non" = { path = "challenge2/non.wasm" }

[[trigger.http]]
route = "/..."
component = "fileserver"

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "static", destination = "/" }]
